# Q1: Import numpy library

In [1]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [2]:
np.linspace(start = 0, stop = 10, num = 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [3]:
import numpy as np  
nums = np.array([[[1.1,2.1,3.1],   
                   [4.1,5.1,6.1]],
                 
                   [[7.1,8.1,9.1],
                   [10.1,11.1,12.1]]]) 
print("Array:")
print(nums)
print("the shape is: ",nums.shape)


Array:
[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]
the shape is:  (2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [4]:
print('type = ', nums.dtype)
print('number of dimensions = ', nums.ndim)
print('shape = ', nums.shape)
print('size = ', nums.size)

type =  float64
number of dimensions =  3
shape =  (2, 2, 3)
size =  12


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [5]:
newarray= np.expand_dims(nums,axis=0)
newarray

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

In [6]:
print("The new diminsion is: ",newarray.ndim)
print("The new shape is: ",newarray.shape)

The new diminsion is:  4
The new shape is:  (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [7]:
xx = newarray.astype(int)
xx.dtype

dtype('int64')

In [8]:
xx

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [9]:
for element in np.nditer(xx):
    print(element, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [10]:
xx[:3,1,0,1]

array([8])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [11]:
xx[:,0,1,1:]

array([[5, 6]])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [12]:
x = np.where(xx==8)
x

(array([0]), array([1]), array([0]), array([1]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [13]:
xx.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [14]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [15]:
newArray = np.concatenate((arr1,arr2))
newArray

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [16]:
np.concatenate((arr1,arr2),axis=1)

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [17]:
qq= np.split(newArray,2,axis=1)
print(qq)

[array([['A'],
       ['E'],
       ['C'],
       ['G']], dtype='<U1'), array([['B'],
       ['F'],
       ['D'],
       ['H']], dtype='<U1')]
