In [1]:
import numpy as np

In [7]:
np.linspace(1,3,num=15,dtype=float)

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ])

In [80]:
new_arr=np.array([
    [[1.1,2.1,3.1],[4.1,5.1,6.1]]
    ,[[7.1,8.1,9.1],[10.1,11.1,12.1]]
])
new_arr

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

In [81]:
new_arr.shape

(2, 2, 3)

In [82]:
type(new_arr)

numpy.ndarray

In [45]:
new_arr.dtype

dtype('float64')

In [66]:
new_arr.itemsize

8

In [65]:
new_arr.size

12

In [72]:
new_arr.ndim

4

In [87]:
arr=new_arr.reshape(2, 1, 2, 3)
arr

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]]],


       [[[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

In [85]:
change_datatyp=arr.astype(int)
change_datatyp

array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])

In [92]:
for x in np.nditer(change_datatyp):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [118]:

eight=change_datatyp[1,0,0,1]
eight

8

In [120]:
five=change_datatyp[0,0,1,1]
five

5

In [122]:
six=change_datatyp[0,0,1,2]
six

6

In [93]:
np.where(change_datatyp == 8)

(array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

In [124]:
change_shape=change_datatyp.reshape(2, 3, 2)

In [111]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
add_arr=np.concatenate((arr1, arr2))
add_arr

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

In [112]:
add_arr_axis=np.concatenate((arr1, arr2),axis=1)
add_arr_axis

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

In [160]:

[arr1,arr2 ]= np.split(add_arr_axis,2, axis= 1)  


In [155]:
arr1

array([['A', 'B'],
       ['E', 'F']], dtype='<U1')

In [156]:
arr2

array([['C', 'D'],
       ['G', 'H']], dtype='<U1')