In [1]:
#Q1: Import numpy library
import numpy as np

In [5]:
#Q2: Generate a sequence of 15 floats using linspace() function
np.linspace(0,15,7)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. ])

In [33]:
#Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below

x = np.array([[[1.1, 2.2,3.3], [3.3, 4.4,3.3]],[[5.5, 6.6,3.3], [7.7, 8.8,3.3]]])
x.shape

(2, 2, 3)

In [34]:
#Q4: Print the following
#Array's type.
#Array's elements datatype.
#Array's shape.
#Array's size.
#Array's dimention.
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)
print(x.data)

type =  float64
number of dimensions =  3
shape =  (2, 2, 3)
size =  12


In [39]:
#Q5: Change the array dimention from 3-D to 4-D
y=np.reshape(x,x.shape+(1,))
y
#Print the new array's dimention and shape
print('number of dimensions = ', y.ndim)
print('shape = ', y.shape)
y

number of dimensions =  4
shape =  (2, 2, 3, 1)


array([[[[1.1],
         [2.2],
         [3.3]],

        [[3.3],
         [4.4],
         [3.3]]],


       [[[5.5],
         [6.6],
         [3.3]],

        [[7.7],
         [8.8],
         [3.3]]]])

In [37]:
#Q6: Change the array's elements datatype to integer
y_int=y.astype(int)
y_int

array([[[[1],
         [2],
         [3]],

        [[3],
         [4],
         [3]]],


       [[[5],
         [6],
         [3]],

        [[7],
         [8],
         [3]]]])

In [40]:
#Q7: Print all array's elements using for loop
for x in np.nditer(y_int):
      print(x)

1
2
3
3
4
3
5
6
3
7
8
3


In [76]:
#Q8: Print number 8 using array slicing
print(y_int[1,-1:2,1:-1])

[[[8]]]


In [79]:
#Q9: Print number 5 and number 6 using array slicing
print(y_int[1,0:1,1:-1])
print(y_int[1,0:1,0:-2])

[[[6]]]
[[[5]]]


In [62]:
#Q10: Search for number 8 using where()
#Note: use the same array from Q6.

#Note: where() is only used with small data.

#the output represents the path of the index that leads to number 8
s = np.where(y_int>7)
print(y_int[s])

[8]


In [52]:
#Q11: Reshape the array as the following
n=y_int.reshape(2, 3,2 )
n

array([[[1, 2],
        [3, 3],
        [4, 3]],

       [[5, 6],
        [3, 7],
        [8, 3]]])

In [53]:
#Q12: Join the given arrays below
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])


In [58]:
#Q12.1: Join the arrays without specifying the axis
m=np.row_stack((arr1,arr2))
m

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

In [57]:
#Q12.2: Join the arrays along rows with axis = 1
g = np.concatenate((arr1, arr2), axis=1)
g

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

In [59]:
#Q13: Split the array into two arrays with axis = 1, each array should contain four arrays.
u = np.array_split(m, 3, axis=1)
u

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1'),
 array([], shape=(4, 0), dtype='<U1')]