# Q1: Import numpy library

In [19]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [20]:
# write your code here ^_^
A = np.linspace(1,20,15)
A.size
A

array([ 1.        ,  2.35714286,  3.71428571,  5.07142857,  6.42857143,
        7.78571429,  9.14285714, 10.5       , 11.85714286, 13.21428571,
       14.57142857, 15.92857143, 17.28571429, 18.64285714, 20.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [21]:
# write your code here ^_^
B = np.arange(1,13).reshape(2,2,3) + .1
B


array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [22]:
# write your code here ^_^
print(type(B))
print(B.dtype)
print(B.shape)
print(B.size)
print(B.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [23]:
# write your code here ^_^
B4 = B.reshape(2,3,1,2)
print(B4)
print("B4 shape ",B4.shape)
print("B4 dimention ",B4.ndim)

[[[[ 1.1  2.1]]

  [[ 3.1  4.1]]

  [[ 5.1  6.1]]]


 [[[ 7.1  8.1]]

  [[ 9.1 10.1]]

  [[11.1 12.1]]]]
B4 shape  (2, 3, 1, 2)
B4 dimention  4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [24]:
# write your code here ^_^
B=B.astype(int)
B

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()


In [25]:
# write your code here ^_^
for x in np.nditer(B):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [32]:
# write your code here ^_^
B[1:2,:1,1:2]

array([[[8]]])

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [33]:

# write your code here ^_^
B[:1,1:,1:]

array([[[5, 6]]])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [49]:
# write your code here ^_^
result = np.where(B==8)
result = np.array(result)
print(result)

[[1]
 [0]
 [1]]


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [51]:

# write your code here ^_^
B3 = B.reshape(2,3,2)
B3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [60]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
print(arr1)
print(arr2)

[['A' 'B']
 ['E' 'F']]
[['C' 'D']
 ['G' 'H']]


In [57]:
arr = np.stack((arr1,arr2))
arr

array([[['A', 'B'],
        ['E', 'F']],

       [['C', 'D'],
        ['G', 'H']]], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [58]:
# write your code here ^_^
np.stack((arr1,arr2),axis=1)

array([[['A', 'B'],
        ['C', 'D']],

       [['E', 'F'],
        ['G', 'H']]], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [86]:
# write your code here ^_^
d,v = np.split(arr,2,axis=1)
print(d)
print(v)


[[['A' 'B']]

 [['C' 'D']]]
[[['E' 'F']]

 [['G' 'H']]]
