# Q1: Import numpy library

In [3]:
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [6]:
z = np.linspace(0,10,15)
z

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [53]:
x = np.array([[[1.1, 2.1, 3.1],[4.1, 5.1, 6.1]],[[7.1,8.1,9.1],[10.1,11.1,12.1]]])
print (x)
print(x.shape)

[[[ 1.1  2.1  3.1]
  [ 4.1  5.1  6.1]]

 [[ 7.1  8.1  9.1]
  [10.1 11.1 12.1]]]
(2, 2, 3)


# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [30]:
print('Array type = ', type(x))
print('elements datatype = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

Array type =  <class 'numpy.ndarray'>
elements datatype =  float64
number of dimensions =  3
shape =  (2, 2, 3)
size =  12


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [49]:
x4 = np.array([[[1.1, 2.1, 3.1],[4.1, 5.1, 6.1]],[[7.1,8.1,9.1],[10.1,11.1,12.1]]], ndmin=4)
print('number of dimensions = ', x4.ndim)
print('shape = ', x4.shape)

number of dimensions =  4
shape =  (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [62]:
intx = x4.astype(int)
intx

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [64]:
for x in np.nditer(intx):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [70]:
intx[[0,1] , 0:1]

IndexError: index 1 is out of bounds for axis 0 with size 1

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [87]:
intx[[0,2] , 1]

IndexError: index 2 is out of bounds for axis 0 with size 1

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [69]:
s = np.where(intx == 8)

print(s)

(array([0], dtype=int64), array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [71]:
intx.reshape(2,3, 2)


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [72]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [79]:
r = np.stack((arr1, arr2))
r

array([[['A', 'B'],
        ['E', 'F']],

       [['C', 'D'],
        ['G', 'H']]], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [73]:
np.row_stack((arr1, arr2))

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [83]:
[B,C] = np.split(r, 2, axis=1)
B

array([[['A', 'B']],

       [['C', 'D']]], dtype='<U1')

In [84]:
C

array([[['E', 'F']],

       [['G', 'H']]], dtype='<U1')