# Q1: Import numpy library

In [52]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [53]:
# write your code here ^_^
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [54]:
# write your code here ^_^
x=np.array([[[1.1,2.1,3.1],
           [4.1,5.1,6.1]],
           [[7.1,8.1,9.1],
           [10.1,11.1,12.1]]])
x

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [55]:
# write your code here ^_^
type(x)

numpy.ndarray

In [56]:
x.dtype

dtype('float64')

In [57]:
x.shape

(2, 2, 3)

In [58]:
x.size

12

In [59]:
x.ndim

3

# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [60]:
# write your code here ^_^
y = np.expand_dims(x.copy(),axis=0)

In [61]:
y.shape

(1, 2, 2, 3)

In [62]:
y.ndim

4

# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [73]:
# write your code here ^_^
new_x=x.copy().astype('int32')

In [74]:
new_x.dtype

dtype('int32')

In [90]:
new_x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [75]:
# write your code here ^_^
for item in np.nditer(new_x):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [79]:
# write your code here ^_^
new_x[1,0,1]

8

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [80]:
# write your code here ^_^
new_x[0,1,1:]

array([5, 6])

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [91]:
# write your code here ^_^
np.where(new_x == 8)

(array([1], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [92]:
# write your code here ^_^
new_x.reshape([2,3,2])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [103]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
new_arr=np.concatenate([arr1,arr2])
new_arr

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [104]:
# write your code here ^_^
np.concatenate([arr1,arr2],axis=1)


array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [107]:
# write your code here ^_^
np.split(new_arr,2,axis=1)

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]