In [2]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [7]:
X = np.ones((2,2))
X

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [8]:
Y = np.zeros((2,2))
Y

array([[0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [10]:
C = X+Y
C

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [13]:
print(X.shape)
print(X.ndim)
print(X.size)
print(type(X))

(2, 2)
2
4
<class 'numpy.ndarray'>


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [89]:
w = np.arange(11,17).reshape(3,2)
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [90]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [91]:
# connot combine in vertical way , cannot combine (3,2) matrix with (1,3) matrix
# first reshape z into (3,1) then combine it horzintaly
z = z.reshape(3,1)
newArray = np.hstack((z,w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [92]:
for lst in newArray:
    for i in lst:
        print(i)

1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [93]:
 newArray.transpose()


array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

## Q#10: Decrement all elements of "newArray" with 1.

In [94]:
newArray -=1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [95]:
# increment newArray with one
#newArray +=1

## Q#11: Find smallest and biggest values in "newArray".

In [96]:
print(newArray.max())
print(newArray.min())

15
0


## Q#12: Print the first row of "newArray" using indexing.

In [97]:
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [98]:
print(newArray[1,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [99]:
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

In [101]:
print(newArray[:2][:])

[[ 0 10 11]
 [ 1 12 13]]


## Q#15: Change the shape of "newArray" to (9,1).

In [102]:
newArray = newArray.reshape(9,1)
newArray

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [103]:
# cannot reshape the newArray into (3,2)
# it has to be the size of the newArray 9
# so the only shapes that can be for newArray are: (9,1), (1,9) and (3,3)
newArray = newArray.reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉