# Q1: Import numpy library

In [90]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [91]:
# write your code here ^_^
array1 = np.linspace(0,20,15) #start at 0 and ends at 20 
array1

array([ 0.        ,  1.42857143,  2.85714286,  4.28571429,  5.71428571,
        7.14285714,  8.57142857, 10.        , 11.42857143, 12.85714286,
       14.28571429, 15.71428571, 17.14285714, 18.57142857, 20.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [92]:
# write your code here ^_^
array_3D = np.array([
    [
        [1.1, 2.1, 3.1],
        [4.1, 5.1, 6.1]
    ],
    [
        [7.1, 8.1, 9.1],
        [10.1, 11.1, 12.1]

    ]

])
array_3D

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [93]:
# write your code here ^_^
print("type of array: ", type(array_3D))
print("type of data in array: ", array_3D.dtype)
print("shape of array: ", array_3D.shape)
print("size of array: ", array_3D.size)
print("dimensions of array: ", array_3D.ndim)

type of array:  <class 'numpy.ndarray'>
type of data in array:  float64
shape of array:  (2, 2, 3)
size of array:  12
dimensions of array:  3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [94]:
# write your code here ^_^

#First Solution
# array_4D = np.reshape(array_3D,(1,2,2,3))


#Second Solution
array_4D = np.array([
    [
        [        
            [1.1, 2.1, 3.1],
            [4.1, 5.1, 6.1]
        ],
        [
            [7.1, 8.1, 9.1],
            [10.1, 11.1, 12.1]

        ]
    ]

])
print("Dimensions: ",array_4D.ndim)
print("Shape: ", array_4D.shape)

Dimensions:  4
Shape:  (1, 2, 2, 3)


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [95]:
# write your code here ^_^
array_4D = array_4D.astype('int64')
array_4D

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]], dtype=int64)

# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [96]:
# write your code here ^_^
for value in np.nditer(array_4D):
    print(value)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [98]:
# write your code here ^_^
array_4D[[0],[1],[0],[1]]

array([8], dtype=int64)

# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [101]:
# write your code here ^_^
array_4D[[0],[0],[1],[1,2]] #[1st-d, 2nd-d, 3rd-d, 4th-d]

array([5, 6], dtype=int64)

# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [103]:
# write your code here ^_^
np.where(array_4D==8)

(array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [104]:
# write your code here ^_^
array_4D = np.reshape(array_4D,(1,3,2,2))
array_4D

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]]], dtype=int64)

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [105]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [106]:
joined_arr = np.stack((arr1,arr2))
joined_arr

array([[['A', 'B'],
        ['E', 'F']],

       [['C', 'D'],
        ['G', 'H']]], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [107]:
# write your code here ^_^
joined_arr2 = np.stack((arr1,arr2), axis=1)
joined_arr2

array([[['A', 'B'],
        ['C', 'D']],

       [['E', 'F'],
        ['G', 'H']]], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [108]:
# write your code here ^_^
siplitted = np.array_split(joined_arr, 2, axis=1)
siplitted

[array([[['A', 'B'],
         ['E', 'F']]], dtype='<U1'),
 array([[['C', 'D'],
         ['G', 'H']]], dtype='<U1')]

In [109]:
# another way to split
siplitted2= np.split(joined_arr,2,axis=1)
siplitted2

[array([[['A', 'B']],
 
        [['C', 'D']]], dtype='<U1'),
 array([[['E', 'F']],
 
        [['G', 'H']]], dtype='<U1')]