In [3]:
#Q1: Import numpy library
import numpy as np

In [55]:
#Q2: Generate a sequence of 15 floats using linspace() function
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [56]:
#Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below
a3D=np.array([
               [
                   [1.1,2.1,3.1],
                   [4.1,5.1,6.1]
               ],
               [
                   [7.1,8.1,9.1],
                   [10.1,11.1,12.1]
               ]
             ])
a3D


array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

In [8]:
#Q4: Print the following:
#Note: use the same array from Q3.
#Array's type.
#Array's elements datatype.
#Array's shape.
#Array's size.
#Array's dimention.

type(a3D)

numpy.ndarray

In [9]:
a3D.dtype

dtype('float64')

In [10]:
a3D.shape

(2, 2, 3)

In [11]:
a3D.size

12

In [12]:
a3D.ndim

3

In [17]:
#Q5: Change the array dimention from 3-D to 4-D
#Note: use the same array from Q3.
#Create a new array to hold the changes.
#Print the new array's dimention and shape.

a4D =np.expand_dims(a3D.copy(),axis=0)


array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

In [18]:
a4D.shape

(1, 2, 2, 3)

In [19]:
a4D.ndim

4

In [32]:
#Q6: Change the array's elements datatype to integer
#Note: use the same array from Q5.

#Create a new array to hold the changes.
#Print the new array.

x=a3D.copy().astype('int32')
x.dtype


dtype('int32')

In [38]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)

In [35]:
#Q7: Print all array's elements using for loop
#Note: use the same array from Q6.
#Hint: use nditer()
for item in np.nditer(x):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [36]:
#Q8: Print number 8 using array slicing
#Note: use the same array from Q6.

x[1,0,1]

8

In [37]:
#Q9: Print number 5 and number 6 using array slicing
#Note: use the same array from Q6.

x[0,1,1:]

array([5, 6], dtype=int32)

In [39]:
#Q10: Search for number 8 using where()
#Note: use the same array from Q6.

#Note: where() is only used with small data.

#the output represents the path of the index that leads to number 8

np.where(x==8)


(array([1]), array([0]), array([1]))

In [43]:
#Q11: Reshape the array as the following
#Note: use the same array from Q6.
x.reshape([2,3,2])

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)

In [61]:
#Q12: Join the given arrays below
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
NewArray=np.concatenate([arr1,arr2])
NewArray

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

In [47]:
#Q12.2: Join the arrays along rows with axis = 1
NewArray=np.concatenate([arr1,arr2],axis=1)
NewArray

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

In [49]:
#Q13: Split the array into two arrays with axis = 1, each array should contain four arrays.
#Note: use the same array from Q12.1
NewArray=np.concatenate([arr1,arr2])
NewArray
np.split(NewArray,2,axis=1)

[array([['A'],
        ['E'],
        ['C'],
        ['G']], dtype='<U1'),
 array([['B'],
        ['F'],
        ['D'],
        ['H']], dtype='<U1')]