# Q1: Import numpy library

In [174]:
# write your code here ^_^
import numpy as np

# Q2: Generate a sequence of 15 floats using linspace() function

In [175]:
# write your code here ^_^
np.linspace(0,50,15)

array([ 0.        ,  3.57142857,  7.14285714, 10.71428571, 14.28571429,
       17.85714286, 21.42857143, 25.        , 28.57142857, 32.14285714,
       35.71428571, 39.28571429, 42.85714286, 46.42857143, 50.        ])

# Q3: Create a 3-D array in shape (2, 2, 3) containing the four arrays given below 
Note : the array's name is up to you.

|      |       |          |         |
|------| ----- | -------- | ------- |
|arr1 | 1.1    | 2.1       | 3.1        |
|arr2 | 4.1    | 5.1       | 6.1        |
|arr3 | 7.1    | 8.1       | 9.1        |
|arr4 | 10.1   | 11.1      | 12.1       |

In [176]:
# write your code here ^_^
Array3D=np.array([
    [
    [1.1, 2.1, 3.1], 
    [4.1, 5.1, 6.1],
    ],
    
    [
    [7.1, 8.1, 9.1],
    [10.1,11.1,12.1]
    ]

])
Array

array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

# Q4: Print the following:
Note: use the same array from Q3.
- Array's type.
- Array's elements datatype.
- Array's shape.
- Array's size.
- Array's dimention.

In [177]:
# write your code here ^_^
print(type(Array3D))
print(Array3D.dtype)
print(Array3D.shape)
print(Array3D.size)
print(Array3D.ndim)

<class 'numpy.ndarray'>
float64
(2, 2, 3)
12
3


# Q5:  Change the array dimention from 3-D to 4-D
Note: use the same array from Q3.
- Create a new array to hold the changes. 
- Print the new array's dimention and shape.

In [178]:
# write your code here ^_^
Array4D=Array3D.copy()
Array4D=newArray4D.reshape(2,1,2,3)
print(Array4D)
print(type(Array4D))
print(Array4D.dtype)
print(Array4D.shape)
print(Array4D.size)
print(Array4D.ndim)


[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]]


 [[[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
<class 'numpy.ndarray'>
float64
(2, 1, 2, 3)
12
4


In [179]:
# write your code here ^_^
newArray4D2=Array3D.copy()
newArray4D2=newArray4D2.reshape(1,2,2,3)
print(newArray4D2)
print(type(newArray4D2))
print(newArray4D2.dtype)
print(newArray4D2.shape)
print(newArray4D2.size)
print(newArray4D2.ndim)

[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
<class 'numpy.ndarray'>
float64
(1, 2, 2, 3)
12
4


In [180]:
D4= np.expand_dims(Array3D.copy(),axis=0)
D4
print(D4)
print(type(D4))
print(D4.dtype)
print(D4.shape)
print(D4.size)
print(D4.ndim)

[[[[ 1.1  2.1  3.1]
   [ 4.1  5.1  6.1]]

  [[ 7.1  8.1  9.1]
   [10.1 11.1 12.1]]]]
<class 'numpy.ndarray'>
float64
(1, 2, 2, 3)
12
4


# Q6: Change the array's elements datatype to integer  
Note: use the same array from Q5.

- Create a new array to hold the changes. 
- Print the new array.

In [181]:
# write your code here ^_^
copyNewArray4D=newArray4D2.copy()
copyNewArray4D=copyNewArray4D.astype('int32')
print(copyNewArray4D)
print(copyNewArray4D.dtype)

[[[[ 1  2  3]
   [ 4  5  6]]

  [[ 7  8  9]
   [10 11 12]]]]
int32


# Q7: Print all array's elements using for loop
Note: use the same array from Q6.

Hint: use nditer()

In [182]:
# write your code here ^_^

for item in np.nditer(copyNewArray4D):
    print(item)

1
2
3
4
5
6
7
8
9
10
11
12


# Q8:  Print number 8 using array slicing
Note: use the same array from Q6.

In [183]:
# write your code here ^_^
#Q6
print(copyNewArray4D[0,1,0,1])
#Q3
# Array3D[1,0,1]

8


# Q9: Print number 5 and number 6 using array slicing
Note: use the same array from Q6.

In [184]:
# write your code here ^_^
print(copyNewArray4D[0,0,1,1:])

[5 6]


# Q10: Search for number 8 using where()
Note: use the same array from Q6.

Note: where() is only used with small data.

*the output represents the path of the index that leads to number 8*

In [185]:
# write your code here ^_^
np.where(copyNewArray4D==8)

(array([0]), array([1]), array([0]), array([1]))

# Q11: Reshape the array as the following

    array([[[ 1, 2],
            [ 3,  4],
            [ 5,  6]],

           [[ 7,  8],
            [ 9, 10],
            [11, 12]]])
            
 Note: use the same array from Q6.

In [186]:
# write your code here ^_^
copyNewArray4D=copyNewArray4D.reshape(2,3,2)
copyNewArray4D

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]], dtype=int32)

# Q12: Join the given arrays below 
    arr1 = np.array([['A', 'B'], ['E', 'F']])
    arr2 = np.array([['C', 'D'], ['G', 'H']])
## Q12.1: Join the arrays without specifying the axis 

In [187]:
# write your code here ^_^
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])
arr = np.concatenate((arr1, arr2))
arr

array([['A', 'B'],
       ['E', 'F'],
       ['C', 'D'],
       ['G', 'H']], dtype='<U1')

# Q12.2: Join the arrays along rows with axis = 1 

In [188]:
# write your code here ^_^
arrAxis1 = np.concatenate((arr1, arr2), axis=1)
arrAxis1

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

# Q13: Split the array into two arrays with axis = 1, each array should contain four arrays. 
Note: use the same array from Q12.1

In [189]:
# write your code here ^_^
[A1,A2] = np.split(arr,2,axis=1)
print(A1)
print(A2)

[['A']
 ['E']
 ['C']
 ['G']]
[['B']
 ['F']
 ['D']
 ['H']]
